// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADmm9_KCrcQhFdECGRr74fS_cwQHErQF8',
    appId: '1:554050595091:web:66f6f98ca3e64c587612e6',
    messagingSenderId: '554050595091',
    projectId: 'ubii-ffcc0',
    authDomain: 'ubii-ffcc0.firebaseapp.com',
    storageBucket: 'ubii-ffcc0.firebasestorage.app',
    measurementId: 'G-K0QJLLYC5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaaDeeKQHzH1d9uwWkHrLJGby2Z5Ai63E',
    appId: '1:554050595091:android:8836c4d58e2cd1597612e6',
    messagingSenderId: '554050595091',
    projectId: 'ubii-ffcc0',
    storageBucket: 'ubii-ffcc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy0Kx9_3YG_b6DP1J0FsDy5vCKXaGd4yM',
    appId: '1:554050595091:ios:3fb0c7f1dd7d9ebd7612e6',
    messagingSenderId: '554050595091',
    projectId: 'ubii-ffcc0',
    storageBucket: 'ubii-ffcc0.firebasestorage.app',
    iosBundleId: 'com.example.ubiint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy0Kx9_3YG_b6DP1J0FsDy5vCKXaGd4yM',
    appId: '1:554050595091:ios:3fb0c7f1dd7d9ebd7612e6',
    messagingSenderId: '554050595091',
    projectId: 'ubii-ffcc0',
    storageBucket: 'ubii-ffcc0.firebasestorage.app',
    iosBundleId: 'com.example.ubiint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADmm9_KCrcQhFdECGRr74fS_cwQHErQF8',
    appId: '1:554050595091:web:ef691a71e68a054d7612e6',
    messagingSenderId: '554050595091',
    projectId: 'ubii-ffcc0',
    authDomain: 'ubii-ffcc0.firebaseapp.com',
    storageBucket: 'ubii-ffcc0.firebasestorage.app',
    measurementId: 'G-XNLJM68HFG',
  );

}